# fly.toml file generated for alice-discord-bot on 2022-08-27T11:51:25+10:00

app = "alice-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
